### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.egzosn.pay.common.util.sign.SignUtils.签名方式

### ISSUE THREAD

**Issue by Cargowu** [egzosn/pay-java-parent#15]
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.egzosn.pay.common.util.sign.SignUtils.签名方式
	at java.lang.Enum.valueOf(Unknown Source)
	at com.egzosn.pay.common.util.sign.SignUtils.valueOf(SignUtils.java:1)
	at com.egzosn.pay.common.api.BasePayService.createSign(BasePayService.java:101)
	at com.egzosn.pay.ali.api.AliPayService.setSign(AliPayService.java:138)
	at com.egzosn.pay.ali.api.AliPayService.orderInfo(AliPayService.java:155)
	at com.egzosn.pay.ali.api.AliPayService.genQrPay(AliPayService.java:276)
	at PayTest.main(PayTest.java:44)

**Comment by egzosn** [comment]
你需要认真看下文档，便于解决签名方式这个问题
