### ISSUE TITLE
hello,考虑支持jdk11吗

### ISSUE THREAD

**Issue by fengxiaobu** [egzosn/pay-java-parent#95]
在jdk11使用出现错误
支付错误: errcode=IOException, errmsg=class org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey cannot be cast to class java.security.interfaces.XECPublicKey (org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @377dca04; java.security.interfaces.XECPublicKey is in module java.base of loader 'bootstrap')

**Comment by egzosn** [comment]
好的，提供下jdk11的细版本

**Comment by fengxiaobu** [comment]
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

**Comment by wxj127** [comment]
jdk21 报错：
com.egzosn.pay.common.exception.PayErrorException: 支付错误: errcode=IOException, errmsg=Could not generate XDH keypair
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:450)
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:483)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.doExecuteEntity(DefaultWxPayAssistService.java:89)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.doExecute(DefaultWxPayAssistService.java:103)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.refreshCertificate(DefaultWxPayAssistService.java:173)
        at com.egzosn.pay.wx.v3.api.WxPayService.getAssistService(WxPayService.java:132)
        at com.egzosn.pay.wx.v3.api.WxPayService.setApiServerUrl(WxPayService.java:162)
        at com.egzosn.pay.wx.v3.api.WxPayService.initAfter(WxPayService.java:148)
        at com.egzosn.pay.wx.v3.api.WxPayService.<init>(WxPayService.java:118)
        at com.egzosn.pay.wx.v3.api.WxPayService.<init>(WxPayService.java:104)
        at com.egzosn.pay.spring.boot.core.provider.merchant.platform.WxV3PaymentPlatform.getPayService(WxV3PaymentPlatform.java:107)
        at com.egzosn.pay.spring.boot.core.merchant.bean.CommonPaymentPlatformMerchantDetails.initService(CommonPaymentPlatformMerchantDetails.java:121)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.lambda$loadMerchantByMerchantId$0(JdbcMerchantDetailsManager.java:167)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:733)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:825)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.loadMerchantByMerchantId(JdbcMerchantDetailsManager.java:139)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.loadMerchantByMerchantId(JdbcMerchantDetailsManager.java:33)
        at com.egzosn.pay.spring.boot.core.provider.CacheMerchantDetailsManager.loadMerchantByMerchantId(CacheMerchantDetailsManager.java:119)
        at com.egzosn.pay.spring.boot.core.provider.CacheMerchantDetailsManager.loadMerchantByMerchantId(CacheMerchantDetailsManager.java:22)
        at com.egzosn.pay.spring.boot.core.MerchantPayServiceManager.getQrPay(MerchantPayServiceManager.java:185)
        at com.media.expense.service.driver.WxPayDriver.execute(WxPayDriver.java:64)
        at com.media.expense.controller.PayController.getQrPay(PayController.java:121)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: javax.net.ssl.SSLException: Could not generate XDH keypair
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:132)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:443)
        ... 79 common frames omitted
Caused by: java.lang.RuntimeException: Could not generate XDH keypair
        at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:109)
        at java.base/sun.security.ssl.NamedGroup$XDHScheme.createPossession(NamedGroup.java:733)
        at java.base/sun.security.ssl.NamedGroup$NamedGroupSpec.createPossession(NamedGroup.java:642)
        at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:550)
        at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:573)
        at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:92)
        at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.getShare(KeyShareExtension.java:295)
        at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:257)
        at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:599)
        at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:265)
        at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:635)
        at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:526)
        at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:263)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
        ... 93 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: XDH KeyPairGenerator not available
        at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:237)
        at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:103)
        ... 107 common frames omitted
13:40:31.697 [http-nio-9090-exec-5] ERROR c.m.c.s.h.GlobalExceptionHandler - [handleRuntimeException,106] - 请求地址'/pay/getQrPay',发生未知异常.
com.egzosn.pay.common.exception.PayErrorException: 支付错误: errcode=IOException, errmsg=Could not generate XDH keypair
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:450)
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:483)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.doExecuteEntity(DefaultWxPayAssistService.java:89)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.doExecute(DefaultWxPayAssistService.java:103)
        at com.egzosn.pay.wx.v3.api.DefaultWxPayAssistService.refreshCertificate(DefaultWxPayAssistService.java:173)
        at com.egzosn.pay.wx.v3.api.WxPayService.getAssistService(WxPayService.java:132)
        at com.egzosn.pay.wx.v3.api.WxPayService.setApiServerUrl(WxPayService.java:162)
        at com.egzosn.pay.wx.v3.api.WxPayService.initAfter(WxPayService.java:148)
        at com.egzosn.pay.wx.v3.api.WxPayService.<init>(WxPayService.java:118)
        at com.egzosn.pay.wx.v3.api.WxPayService.<init>(WxPayService.java:104)
        at com.egzosn.pay.spring.boot.core.provider.merchant.platform.WxV3PaymentPlatform.getPayService(WxV3PaymentPlatform.java:107)
        at com.egzosn.pay.spring.boot.core.merchant.bean.CommonPaymentPlatformMerchantDetails.initService(CommonPaymentPlatformMerchantDetails.java:121)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.lambda$loadMerchantByMerchantId$0(JdbcMerchantDetailsManager.java:167)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:733)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:825)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.loadMerchantByMerchantId(JdbcMerchantDetailsManager.java:139)
        at com.egzosn.pay.spring.boot.core.provider.JdbcMerchantDetailsManager.loadMerchantByMerchantId(JdbcMerchantDetailsManager.java:33)
        at com.egzosn.pay.spring.boot.core.provider.CacheMerchantDetailsManager.loadMerchantByMerchantId(CacheMerchantDetailsManager.java:119)
        at com.egzosn.pay.spring.boot.core.provider.CacheMerchantDetailsManager.loadMerchantByMerchantId(CacheMerchantDetailsManager.java:22)
        at com.egzosn.pay.spring.boot.core.MerchantPayServiceManager.getQrPay(MerchantPayServiceManager.java:185)
        at com.media.expense.service.driver.WxPayDriver.execute(WxPayDriver.java:64)
        at com.media.expense.controller.PayController.getQrPay(PayController.java:121)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: javax.net.ssl.SSLException: Could not generate XDH keypair
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:132)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.egzosn.pay.common.http.HttpRequestTemplate.doExecuteEntity(HttpRequestTemplate.java:443)
        ... 79 common frames omitted
Caused by: java.lang.RuntimeException: Could not generate XDH keypair
        at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:109)
        at java.base/sun.security.ssl.NamedGroup$XDHScheme.createPossession(NamedGroup.java:733)
        at java.base/sun.security.ssl.NamedGroup$NamedGroupSpec.createPossession(NamedGroup.java:642)
        at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:550)
        at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:573)
        at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:92)
        at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.getShare(KeyShareExtension.java:295)
        at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:257)
        at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:599)
        at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:265)
        at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:635)
        at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:526)
        at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:263)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
        ... 93 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: XDH KeyPairGenerator not available
        at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:237)
        at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:103)
        ... 107 common frames omitted
